# Generated by Django 2.1.2 on 2019-01-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('New', 'New Vehicle'), ('Used', 'Used Vehicle'), ('Lease', 'Rental Vehicle'), ('faq', 'FAQ')], default='New', max_length=25, verbose_name='Listing Type'),
        ),
    ]
