# Generated by Django 2.1.5 on 2019-02-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carimg',
            old_name='LImage',
            new_name='limage',
        ),
        migrations.RenameField(
            model_name='carimg',
            old_name='MainImage',
            new_name='mainimage',
        ),
    ]
