# Generated by Django 2.1.4 on 2019-01-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimg',
            name='car',
            field=models.ForeignKey(default='car', on_delete=django.db.models.deletion.CASCADE, related_name='cari', to='listing.Car'),
        ),
    ]
