# Generated by Django 2.1.2 on 2018-12-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new',
            new_name='newcar',
        ),
    ]
