# Generated by Django 2.1.2 on 2019-01-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sold',
            field=models.CharField(choices=[('Sale', 'For Sale'), ('Solded', 'Sold')], default='Sale', max_length=10, verbose_name='Sold Y/N'),
        ),
    ]
