# Generated by Django 2.1.2 on 2018-12-10 10:40

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20181210_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Description of New Car'),
        ),
        migrations.AlterField(
            model_name='newcar',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title of Car Listing'),
        ),
    ]
