# Generated by Django 2.1.2 on 2019-01-25 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20190117_0515'),
    ]

    operations = [
        migrations.CreateModel(
            name='faqath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.FileField(null=True, upload_to='listing/ath')),
                ('car', models.ForeignKey(default='car', on_delete=django.db.models.deletion.CASCADE, related_name='carath', to='listing.Car')),
            ],
        ),
    ]
