# Generated by Django 2.1.4 on 2019-01-05 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_carimg_mainimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimg',
            name='MainImage',
            field=models.BooleanField(default=False),
        ),
    ]
