# Generated by Django 2.1.2 on 2018-12-11 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_auto_20181210_1040'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newcar',
            new_name='car',
        ),
    ]
