# Generated by Django 2.1.2 on 2018-12-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_auto_20181211_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Lease', 'Lease')], default='New', max_length=25),
        ),
    ]
