# Generated by Django 2.1.2 on 2018-12-11 04:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_car_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='body',
            field=ckeditor.fields.RichTextField(verbose_name='Description of Vehicle'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title of Vehicle Listing'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Lease', 'Lease')], default='New', max_length=25, verbose_name='Listing Type'),
        ),
    ]
