# Generated by Django 2.1.2 on 2018-12-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_auto_20181211_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price of Vehicle in Dollar Amount'),
        ),
        migrations.AlterField(
            model_name='car',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='SLUG: Your URL will have this in the address'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('New', 'New Vehicle'), ('Used', 'Used Vehicle'), ('Lease', 'Lease Vehicle')], default='New', max_length=25, verbose_name='Listing Type'),
        ),
    ]
