# Generated by Django 2.1.4 on 2018-12-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_auto_20181211_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='LImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
