# Generated by Django 2.1.4 on 2018-12-22 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_car_limage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='LImage',
            field=models.ImageField(blank=True, null=True, upload_to='listing/media/'),
        ),
    ]
