# Generated by Django 2.1.2 on 2018-12-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0011_auto_20181222_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='LImage',
            field=models.ImageField(null=True, upload_to='listing'),
        ),
    ]
