# Generated by Django 2.1.2 on 2018-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0015_auto_20181228_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sold',
            field=models.BooleanField(choices=[('Sale', 'For Sale'), ('Sold', 'Sold')], default='Sale', verbose_name='Sold Y/N'),
        ),
    ]
