# Generated by Django 2.1.2 on 2018-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0016_auto_20181228_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='sold',
            field=models.CharField(choices=[('Sale', 'For Sale'), ('Sold', 'Sold')], default='Sale', max_length=10, verbose_name='Sold Y/N'),
        ),
    ]
