# Generated by Django 2.1.2 on 2018-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0017_auto_20181228_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Title of Vehicle Listing'),
        ),
    ]
