# Generated by Django 2.1.5 on 2019-02-17 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='BImage1',
            new_name='bimage1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='BImage2',
            new_name='bimage2',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='BImage3',
            new_name='bimage3',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='BImage4',
            new_name='bimage4',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='BImage5',
            new_name='bimage5',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Blink1',
            new_name='blink1',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Blink2',
            new_name='blink2',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Blink3',
            new_name='blink3',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Blink4',
            new_name='blink4',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Blink5',
            new_name='blink5',
        ),
        migrations.RenameField(
            model_name='banner',
            old_name='Program',
            new_name='program',
        ),
    ]
