# Generated by Django 2.1.1 on 2019-02-13 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='CalImg1',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Calculator Image 1'),
        ),
    ]
