# Generated by Django 2.1.4 on 2018-12-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='BImage1',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage10',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage2',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage3',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage4',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage5',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage6',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage7',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage8',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage9',
            field=models.ImageField(blank=True, null=True, upload_to='banner'),
        ),
    ]
