# Generated by Django 2.1.2 on 2018-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20181222_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='Blink1',
            field=models.URLField(blank=True, null=True),
        ),
    ]
