# Generated by Django 2.1.1 on 2019-02-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_banner_calimg1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='CalImg1',
        ),
        migrations.AddField(
            model_name='banner',
            name='Program',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Program'),
        ),
        migrations.AddField(
            model_name='banner',
            name='hanin',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Hanin'),
        ),
        migrations.AddField(
            model_name='banner',
            name='leasedeal',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='leasedeal'),
        ),
        migrations.AddField(
            model_name='banner',
            name='migration',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='migration'),
        ),
        migrations.AddField(
            model_name='banner',
            name='rental',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='rental'),
        ),
    ]
