# Generated by Django 2.1.2 on 2018-12-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0005_auto_20181228_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='BImage2',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Banner Image 2'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage3',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Banner Image 3'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage4',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Banner Image 4'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='BImage5',
            field=models.ImageField(null=True, upload_to='banner', verbose_name='Banner Image 5'),
        ),
    ]
